language: c

matrix:
  include:
  - os: linux
    compiler: gcc
    sudo: required

addons:
  apt:
    packages: lcov

before_install:

# Travis branch-specific clone problem workaround:
- git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch

- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    pip install --user scikit-ci-addons==0.15.0;
    ci_addons travis/install_cmake 3.2.0;
  fi

script: tests/run-all-tests.sh

after_script:
  # Create lcov report
  - lcov -c -i -d .. -o app_base.info
  - lcov --capture --directory . --output-file app_test.info
  - lcov --remove coverage.info */tests/* --output-file app_test.info
  - lcov -a app_base.info -a app_test.info -o app_total.info
  - lcov --list coverage.info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
